# Generated by Django 3.0 on 2024-12-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phoneNo', models.CharField(max_length=20, null=True)),
                ('phoneNo1', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadharNo', models.CharField(max_length=12)),
                ('panNo', models.CharField(max_length=10)),
                ('aadharAddress', models.CharField(max_length=255)),
                ('presentAddress', models.CharField(max_length=255)),
                ('phoneNo', models.CharField(max_length=15)),
                ('altphoneNo', models.CharField(blank=True, max_length=15, null=True)),
                ('jamenName', models.CharField(max_length=100)),
                ('jamenAddress', models.CharField(max_length=255)),
                ('jamenNo', models.CharField(max_length=20)),
                ('loanAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serialNo', models.IntegerField(unique=True)),
                ('loanDate', models.DateField()),
                ('loanpayDate', models.IntegerField(null=True)),
                ('loanEnddate', models.DateField()),
                ('loanDayCount', models.IntegerField(null=True)),
                ('loanType', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('interestAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('objectValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('customerImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('jamenImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('serialNo', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('loanType', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('utype', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phoneNo', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNo', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('loanType', models.CharField(max_length=100)),
                ('loanAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interestAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enteredAmt', models.FloatField(null=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahalaxmi_app.Customer')),
            ],
        ),
    ]
