# Generated by Django 3.0 on 2024-12-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalaxmi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='jamenaadharNo',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
