# Generated by Django 3.0 on 2024-12-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalaxmi_app', '0002_customer_jamenaadharno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agreementNo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
