# Generated by Django 3.0 on 2024-12-15 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mahalaxmi_app', '0004_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='interestAmt',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='duration',
            new_name='loanDayCount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loanId',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='serialNo',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mahalaxmi_app.Customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='loan_images/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanAmt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanEnddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanpayDate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='objectValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
