# Generated by Django 3.0 on 2024-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalaxmi_app', '0006_loan_serialno'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
