# Generated by Django 3.0 on 2024-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalaxmi_app', '0008_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerImage',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='jamenImage',
            field=models.ImageField(blank=True, null=True, upload_to='jamen/'),
        ),
    ]
