# Generated by Django 3.0 on 2024-12-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalaxmi_app', '0009_auto_20241217_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadharPdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
